version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: gptbridge_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: gptbridge_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db_data:
    name: gptbridge_db_data

